# Generated by Django 5.1 on 2024-10-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopia_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
